insert into timezones(id, name, description, offset) values (0,'Dateline Standard Time','(GMT-12:00) International Date Line West','-12');
insert into timezones(id, name, description, offset) values (1,'Samoa Standard Time','(GMT-11:00) Midway Island, Samoa','-11');
insert into timezones(id, name, description, offset) values (2,'Hawaiian Standard Time','(GMT-10:00) Hawaii','-10');
insert into timezones(id, name, description, offset) values (3,'Alaskan Standard Time','(GMT-09:00) Alaska','-09');
insert into timezones(id, name, description, offset) values (4,'Pacific Standard Time','(GMT-08:00) Pacific Time (US and Canada); Tijuana','-08');
insert into timezones(id, name, description, offset) values (10,'Mountain Standard Time','(GMT-07:00) Mountain Time (US and Canada)','-07');
insert into timezones(id, name, description, offset) values (13,'Mexico Standard Time 2 ','(GMT-07:00) Chihuahua, La Paz, Mazatlan','-07');
insert into timezones(id, name, description, offset) values (15,'U.S. Mountain Standard Time','(GMT-07:00) Arizona','-07');
insert into timezones(id, name, description, offset) values (20,'Central Standard Time','(GMT-06:00) Central Time (US and Canada','-06');
insert into timezones(id, name, description, offset) values (25,'Canada Central Standard Time','(GMT-06:00) Saskatchewan','-06');
insert into timezones(id, name, description, offset) values (30,'Mexico Standard Time','(GMT-06:00) Guadalajara, Mexico City, Monterrey','-06');
insert into timezones(id, name, description, offset) values (33,'Central America Standard Time','(GMT-06:00) Central America','-06');
insert into timezones(id, name, description, offset) values (35,'Eastern Standard Time','(GMT-05:00) Eastern Time (US and Canada)','-05');
insert into timezones(id, name, description, offset) values (40,'U.S. Eastern Standard Time','(GMT-05:00) Indiana (East)','-05');
insert into timezones(id, name, description, offset) values (45,'S.A. Pacific Standard Time','(GMT-05:00) Bogota, Lima, Quito','-05');
insert into timezones(id, name, description, offset) values (50,'Atlantic Standard Time','(GMT-04:00) Atlantic Time (Canada)','-04');
insert into timezones(id, name, description, offset) values (55,'S.A. Western Standard Time','(GMT-04:00) Caracas, La Paz','-04');
insert into timezones(id, name, description, offset) values (56,'Pacific S.A. Standard Time','(GMT-04:00) Santiago','-04');
insert into timezones(id, name, description, offset) values (60,'Newfoundland and Labrador Standard Time','(GMT-03:30) Newfoundland and Labrador','-03:30');
insert into timezones(id, name, description, offset) values (65,'E. South America Standard Time','(GMT-03:00) Brasilia','-03');
insert into timezones(id, name, description, offset) values (70,'S.A. Eastern Standard Time','(GMT-03:00) Buenos Aires, Georgetown','-03');
insert into timezones(id, name, description, offset) values (73,'Greenland Standard Time','(GMT-03:00) Greenland','-03');
insert into timezones(id, name, description, offset) values (75,'Mid-Atlantic Standard Time','(GMT-02:00) Mid-Atlantic','-02');
insert into timezones(id, name, description, offset) values (80,'Azores Standard Time','(GMT-01:00) Azores','-01');
insert into timezones(id, name, description, offset) values (83,'Cape Verde Standard Time','(GMT-01:00) Cape Verde Islands','-01');
insert into timezones(id, name, description, offset) values (85,'GMT Standard Time','(GMT) Greenwich Mean Time: Dublin, Edinburgh, Lisbon, London','0');
insert into timezones(id, name, description, offset) values (90,'Greenwich Standard Time','(GMT) Casablanca, Monrovia','0');
insert into timezones(id, name, description, offset) values (95,'Central Europe Standard Time','(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague','+01');
insert into timezones(id, name, description, offset) values (100,'Central European Standard Time','(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb','+01');
insert into timezones(id, name, description, offset) values (105,'Romance Standard Time','(GMT+01:00) Brussels, Copenhagen, Madrid, Paris','+01');
insert into timezones(id, name, description, offset) values (110,'W. Europe Standard Time','(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna','+01');
insert into timezones(id, name, description, offset) values (113,'W. Central Africa Standard Time','(GMT+01:00) West Central Africa','+01');
insert into timezones(id, name, description, offset) values (115,'E. Europe Standard Time','(GMT+02:00) Bucharest','+02');
insert into timezones(id, name, description, offset) values (120,'Egypt Standard Time','(GMT+02:00) Cairo','+02');
insert into timezones(id, name, description, offset) values (125,'FLE Standard Time','(GMT+02:00) Helsinki, Kiev, Riga, Sofia, Tallinn, Vilnius','+02');
insert into timezones(id, name, description, offset) values (130,'GTB Standard Time','(GMT+02:00) Athens, Istanbul, Minsk','+02');
insert into timezones(id, name, description, offset) values (135,'Israel Standard Time','(GMT+02:00) Jerusalem','+02');
insert into timezones(id, name, description, offset) values (140,'South Africa Standard Time','(GMT+02:00) Harare, Pretoria','+02');
insert into timezones(id, name, description, offset) values (145,'Russian Standard Time','(GMT+03:00) Moscow, St. Petersburg, Volgograd','+03');
insert into timezones(id, name, description, offset) values (150,'Arab Standard Time','(GMT+03:00) Kuwait, Riyadh','+03');
insert into timezones(id, name, description, offset) values (155,'E. Africa Standard Time','(GMT+03:00) Nairobi','+03');
insert into timezones(id, name, description, offset) values (158,'Arabic Standard Time','(GMT+03:00) Baghdad','+03');
insert into timezones(id, name, description, offset) values (160,'Iran Standard Time','(GMT+03:30) Tehran','+03:30');
insert into timezones(id, name, description, offset) values (165,'Arabian Standard Time','(GMT+04:00) Abu Dhabi, Muscat','+04');
insert into timezones(id, name, description, offset) values (170,'Caucasus Standard Time','(GMT+04:00) Baku, Tbilisi, Yerevan','+04');
insert into timezones(id, name, description, offset) values (175,'Transitional Islamic State of Afghanistan Standard Time','(GMT+04:30) Kabul','+04:30');
insert into timezones(id, name, description, offset) values (180,'Ekaterinburg Standard Time','(GMT+05:00) Ekaterinburg','+05');
insert into timezones(id, name, description, offset) values (185,'West Asia Standard Time','(GMT+05:00) Islamabad, Karachi, Tashkent','+05');
insert into timezones(id, name, description, offset) values (190,'India Standard Time','(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi','+05:30');
insert into timezones(id, name, description, offset) values (193,'Nepal Standard Time','(GMT+05:45) Kathmandu','+05:45');
insert into timezones(id, name, description, offset) values (195,'Central Asia Standard Time','(GMT+06:00) Astana, Dhaka','+06');
insert into timezones(id, name, description, offset) values (200,'Sri Lanka Standard Time','(GMT+06:00) Sri Jayawardenepura','+06');
insert into timezones(id, name, description, offset) values (201,'N. Central Asia Standard Time','(GMT+06:00) Almaty, Novosibirsk','+06');
insert into timezones(id, name, description, offset) values (203,'Myanmar Standard Time','(GMT+06:30) Yangon Rangoon','+06:30');
insert into timezones(id, name, description, offset) values (205,'S.E. Asia Standard Time','(GMT+07:00) Bangkok, Hanoi, Jakarta','+07');
insert into timezones(id, name, description, offset) values (207,'North Asia Standard Time','(GMT+07:00) Krasnoyarsk','+07');
insert into timezones(id, name, description, offset) values (210,'China Standard Time','(GMT+08:00) Beijing, Chongqing, Hong Kong SAR, Urumqi','+08');
insert into timezones(id, name, description, offset) values (215,'Singapore Standard Time','(GMT+08:00) Kuala Lumpur, Singapore','+08');
insert into timezones(id, name, description, offset) values (220,'Taipei Standard Time','(GMT+08:00) Taipei','+08');
insert into timezones(id, name, description, offset) values (225,'W. Australia Standard Time','(GMT+08:00) Perth','+08');
insert into timezones(id, name, description, offset) values (227,'North Asia East Standard Time','(GMT+08:00) Irkutsk, Ulaanbaatar','+08');
insert into timezones(id, name, description, offset) values (230,'Korea Standard Time','(GMT+09:00) Seoul','+09');
insert into timezones(id, name, description, offset) values (235,'Tokyo Standard Time','(GMT+09:00) Osaka, Sapporo, Tokyo','+09');
insert into timezones(id, name, description, offset) values (240,'Yakutsk Standard Time','(GMT+09:00) Yakutsk','+09');
insert into timezones(id, name, description, offset) values (245,'A.U.S. Central Standard Time','(GMT+09:30) Darwin','+09:30');
insert into timezones(id, name, description, offset) values (250,'Cen. Australia Standard Time','(GMT+09:30) Adelaide','+09:30');
insert into timezones(id, name, description, offset) values (255,'A.U.S. Eastern Standard Time','(GMT+10:00) Canberra, Melbourne, Sydney','+10');
insert into timezones(id, name, description, offset) values (260,'E. Australia Standard Time','(GMT+10:00) Brisbane','+10');
insert into timezones(id, name, description, offset) values (265,'Tasmania Standard Time','(GMT+10:00) Hobart','+10');
insert into timezones(id, name, description, offset) values (270,'Vladivostok Standard Time','(GMT+10:00) Vladivostok','+10');
insert into timezones(id, name, description, offset) values (275,'West Pacific Standard Time','(GMT+10:00) Guam, Port Moresby','+10');
insert into timezones(id, name, description, offset) values (280,'Central Pacific Standard Time','(GMT+11:00) Magadan, Solomon Islands, New Caledonia','+11');
insert into timezones(id, name, description, offset) values (285,'Fiji Islands Standard Time','(GMT+12:00) Fiji Islands, Kamchatka, Marshall Islands','+12');
insert into timezones(id, name, description, offset) values (290,'New Zealand Standard Time','(GMT+12:00) Auckland, Wellington','+12');
insert into timezones(id, name, description, offset) values (300,'Tonga Standard Time','(GMT+13:00) Nuku''alofa','+13');