// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx4V2Nw5S-fNbZh9GSL_VKRz4Utot1em4',
    appId: '1:719024017197:web:4d7dba1a9e16c8ec948da4',
    messagingSenderId: '719024017197',
    projectId: 'yokogawa-dev',
    authDomain: 'yokogawa-dev.firebaseapp.com',
    storageBucket: 'yokogawa-dev.appspot.com',
    measurementId: 'G-TM6ZJRERWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5-8I-MbadFNQfACKYxc8RwxW9uU-un5I',
    appId: '1:719024017197:android:e4ffbe0503ff91b7948da4',
    messagingSenderId: '719024017197',
    projectId: 'yokogawa-dev',
    storageBucket: 'yokogawa-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSG8UlYDHpmlLM6ZcRH8KG8oHYun5rQi4',
    appId: '1:719024017197:ios:8aaf8e054bce21bd948da4',
    messagingSenderId: '719024017197',
    projectId: 'yokogawa-dev',
    storageBucket: 'yokogawa-dev.appspot.com',
    iosBundleId: 'com.yokogawa.alarm.management',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSG8UlYDHpmlLM6ZcRH8KG8oHYun5rQi4',
    appId: '1:719024017197:ios:8aaf8e054bce21bd948da4',
    messagingSenderId: '719024017197',
    projectId: 'yokogawa-dev',
    storageBucket: 'yokogawa-dev.appspot.com',
    iosBundleId: 'com.yokogawa.alarm.management',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx4V2Nw5S-fNbZh9GSL_VKRz4Utot1em4',
    appId: '1:719024017197:web:5fa11a915e382191948da4',
    messagingSenderId: '719024017197',
    projectId: 'yokogawa-dev',
    authDomain: 'yokogawa-dev.firebaseapp.com',
    storageBucket: 'yokogawa-dev.appspot.com',
    measurementId: 'G-YSLSR7G9L3',
  );

}